### ISSUE TITLE
请完成页面抽离

### ISSUE THREAD

**Issue by ZxpKiki** [ZxpKiki/C4#4]
https://github.com/ZxpKiki/Demo4SSIV/commit/a95f1dfdb48c1bffd871e75d1ed4b98f05d75f4d?diff=split#diff-00f26c683c219e66140dfebcd01fba61R51
这是老师给的代码，请仔细查看后，把所有web界面进行抽离。

**Comment by GTZhou** [comment]
完成了？

**Comment by ZxpKiki** [comment]
完成了耶~
